#pragma once
#include <iostream>
#include <string>
#include <string_view>
#include <logx/logx.h>

#define RENDELL_UI_DEBUG_PREFIX "[RENDELL_UI::DEBUG] "
#define RENDELL_UI_ERROR_PREFIX "[RENDELL_UI::ERROR] "
#define RENDELL_UI_WARNING_PREFIX "[RENDELL_UI::WARNING] "

#define RENDELL_UI_DEBUG_WPREFIX L"[RENDELL_UI::DEBUG] "
#define RENDELL_UI_ERROR_WPREFIX L"[RENDELL_UI::ERROR] "
#define RENDELL_UI_WARNING_WPREFIX L"[RENDELL_UI::WARNING] "

#define RUI_DEBUG LOGX_CLOGGER(std::cout, RENDELL_UI_DEBUG_PREFIX, LOGX_WHITE)
#define RUI_ERROR LOGX_CLOGGER(std::cerr, RENDELL_UI_ERROR_PREFIX, LOGX_RED)
#define RUI_WARNING LOGX_CLOGGER(std::cout, RENDELL_UI_WARNING_PREFIX, LOGX_YELLOW)

#define RUI_W_DEBUG LOGX_WLOGGER(std::wcout, RENDELL_UI_DEBUG_WPREFIX, LOGX_WHITE)
#define RUI_W_ERROR LOGX_WLOGGER(std::wcerr, RENDELL_UI_ERROR_WPREFIX, LOGX_RED)
#define RUI_W_WARNING LOGX_WLOGGER(std::wcout, RENDELL_UI_WARNING_WPREFIX, LOGX_YELLOW)

